
#just an example of the naming convention of the profile property file

# Demo connecting to local database
# Assumes username of 'root' with no password
# Use `create database cars;` from the CLI to create the empty DB

spring:
  datasource:
#      url:jdbc: mysql://localhost/cars
#      username: root
     #wont loose the connection
      test-on-borrow: true
      est-while-idle: true
      validation-query: select 1 from sysibm.sysdummy1
      ##end
  jpa:
        hibernate:
          ddl-auto: validate #tell jpa not create schema
