configuration:
  projectName : Spring Boot


#profile-specific properties can also be defined using the naming convention application-{profile}.properties
spring:
    profiles: dev
    #if you want to override property from config server by system property, also see bootstrap.yml
    cloud:
            config:
                allowOverride: true
                failFast: true
                overrideNone: false
                overrideSystemProperties: false
                #            ^--- this has to be false
server:
    port: 9001


